spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    user:
      name: admin
      password: password
      roles: ADMIN

security:
  permit-all-uris:
    - "/"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

logging:
  file:
    name: logs/app.log


